-- Idempotent GOLDLANDS demo seed.
-- Run this in the Supabase SQL Editor after the schema and RLS migrations.
-- It inserts/updates only public.projects and public.apartments.

with project_rows (
  slug,
  name,
  location,
  city,
  neighborhood,
  address,
  google_maps_url,
  google_maps_embed_url,
  project_type,
  marketing_status,
  tagline,
  description,
  logo_mark,
  key_facts,
  floors,
  units,
  occupancy,
  parking_summary,
  buildings,
  existing_apartments,
  new_apartments,
  storage_summary,
  apartment_mix,
  readiness_percentage,
  apartment_offset
) as (
  values
    (
      'gold-tower',
      'GOLD TOWER',
      'פארק צמרת, תל אביב',
      'תל אביב',
      'פארק צמרת',
      'ניסים אלוני 10, תל אביב',
      'https://www.google.com/maps/search/?api=1&query=ניסים+אלוני+10+תל+אביב',
      'https://www.google.com/maps?q=ניסים+אלוני+10+תל+אביב&output=embed',
      'פרויקט חדש',
      'כמעט מוכן להצגה',
      'מגדל מגורים אלגנטי עם חוויית כניסה של מלון פרטי.',
      'פרויקט יוקרה במיקום עירוני מבוקש, עם תכנון מוקפד, לובי מרשים ותמהיל דירות מגוון.',
      'GT',
      array['32 קומות', '124 דירות', 'לובי פרטי', 'חניה תת קרקעית']::text[],
      '32',
      '124',
      'רבעון 4 / 2027',
      '2 קומות',
      '2',
      'לא רלוונטי',
      '124',
      'מחסן לרוב הדירות',
      '{"threeRooms":"24","fourRooms":"52","fiveRooms":"38","gardenApartments":"0","penthouses":"10"}'::jsonb,
      86,
      0
    ),
    (
      'vista-park',
      'VISTA PARK',
      'רמת השרון החדשה',
      'רמת השרון',
      'רמת השרון החדשה',
      'הנוריות 8, רמת השרון',
      'https://www.google.com/maps/search/?api=1&query=הנוריות+8+רמת+השרון',
      'https://www.google.com/maps?q=הנוריות+8+רמת+השרון&output=embed',
      'פרויקט חדש',
      'חסר חומרים חשובים',
      'מגורים ירוקים מול פארק רחב, עם מפרט פרימיום ושקט עירוני.',
      'מתחם מגורים שקט בסביבה ירוקה, עם מרפסות גדולות ונגישות גבוהה לשירותים קהילתיים.',
      'VP',
      array['21 קומות', '88 דירות', 'צמוד לפארק', 'מרפסות גדולות']::text[],
      '21',
      '88',
      'רבעון 2 / 2028',
      'חניה כפולה',
      '1',
      'לא רלוונטי',
      '88',
      'מחסן לכל דירה',
      '{"threeRooms":"18","fourRooms":"34","fiveRooms":"28","gardenApartments":"4","penthouses":"4"}'::jsonb,
      68,
      2
    ),
    (
      'sea-sun',
      'SEA & SUN',
      'קו החוף, נתניה',
      'נתניה',
      'קו החוף',
      'שדרות בן עמי 22, נתניה',
      'https://www.google.com/maps/search/?api=1&query=שדרות+בן+עמי+22+נתניה',
      'https://www.google.com/maps?q=שדרות+בן+עמי+22+נתניה&output=embed',
      'פרויקט חדש',
      'בטיפול שיווק',
      'קו ראשון לאור, רוח וים, עם דירות מרווחות ונוף פתוח.',
      'פרויקט חוף מוקפד עם דגש על אור טבעי, נוף פתוח וחוויית מגורים רגועה ליד הים.',
      'SS',
      array['28 קומות', '96 דירות', 'נוף לים', 'מועדון דיירים']::text[],
      '28',
      '96',
      'רבעון 1 / 2028',
      'חניון פרטי',
      '1',
      'לא רלוונטי',
      '96',
      'מחסנים בקומות חניון',
      '{"threeRooms":"20","fourRooms":"36","fiveRooms":"30","gardenApartments":"0","penthouses":"10"}'::jsonb,
      74,
      4
    ),
    (
      'green-city',
      'GREEN CITY',
      'שכונת נווה גן, פתח תקווה',
      'פתח תקווה',
      'נווה גן',
      'גרינשפן 14, פתח תקווה',
      'https://www.google.com/maps/search/?api=1&query=גרינשפן+14+פתח+תקווה',
      'https://www.google.com/maps?q=גרינשפן+14+פתח+תקווה&output=embed',
      'תמ״א 38/2 / פינוי בינוי',
      'מוכן להצגת בסיס',
      'קהילה משפחתית מתוכננת סביב גינות, מסחר שכונתי וחינוך איכותי.',
      'התחדשות עירונית בשכונה משפחתית, עם דירות חדשות, חניה, מחסנים ופיתוח סביבתי.',
      'GC',
      array['18 קומות', '72 דירות', 'גינות משותפות', 'קרוב לרכבת הקלה']::text[],
      '18',
      '72',
      'רבעון 3 / 2027',
      'חניה ומחסן',
      '2',
      '36',
      '72',
      'מחסן לפי תמהיל',
      '{"threeRooms":"16","fourRooms":"30","fiveRooms":"18","gardenApartments":"4","penthouses":"4"}'::jsonb,
      79,
      6
    ),
    (
      'hills-view',
      'HILLS VIEW',
      'מבשרת ציון',
      'מבשרת ציון',
      'הרכס',
      'הזית 6, מבשרת ציון',
      'https://www.google.com/maps/search/?api=1&query=הזית+6+מבשרת+ציון',
      'https://www.google.com/maps?q=הזית+6+מבשרת+ציון&output=embed',
      'תמ״א 38/1',
      'טיוטה ראשונית',
      'מגורים גבוהים מול נוף פתוח, עם דגש על פרטיות ואוויר הרים.',
      'פרויקט אינטימי מול נוף פתוח, המשלב שדרוג מבנה קיים עם תוספת דירות חדשות.',
      'HV',
      array['16 קומות', '64 דירות', 'נוף פתוח', 'מפרט שקט']::text[],
      '16',
      '64',
      'רבעון 4 / 2028',
      'חניה מקורה',
      '1',
      '32',
      '64',
      'מחסן לחלק מהדירות',
      '{"threeRooms":"14","fourRooms":"28","fiveRooms":"16","gardenApartments":"2","penthouses":"4"}'::jsonb,
      51,
      8
    ),
    (
      'next-tlv',
      'NEXT TLV',
      'מתחם חסן ערפה, תל אביב',
      'תל אביב',
      'מתחם חסן ערפה',
      'יצחק שדה 18, תל אביב',
      'https://www.google.com/maps/search/?api=1&query=יצחק+שדה+18+תל+אביב',
      'https://www.google.com/maps?q=יצחק+שדה+18+תל+אביב&output=embed',
      'פרויקט חדש',
      'מוכן להצגה',
      'כתובת עירונית חדה לאנשים שרוצים להיות קרובים לכל דבר.',
      'פרויקט עירוני במתחם מתחדש, קרוב לצירי תנועה, מסחר, משרדים וחיי העיר.',
      'NT',
      array['24 קומות', '110 דירות', 'עירוב שימושים', 'לובי עסקים']::text[],
      '24',
      '110',
      'רבעון 2 / 2027',
      'חניון אוטומטי',
      '1',
      'לא רלוונטי',
      '110',
      'מחסנים נבחרים',
      '{"threeRooms":"26","fourRooms":"44","fiveRooms":"30","gardenApartments":"0","penthouses":"10"}'::jsonb,
      94,
      10
    )
),
upserted_projects as (
  insert into public.projects (
    slug,
    name,
    location,
    city,
    neighborhood,
    address,
    google_maps_url,
    google_maps_embed_url,
    project_type,
    marketing_status,
    tagline,
    description,
    logo_mark,
    key_facts,
    floors,
    units,
    occupancy,
    parking_summary,
    buildings,
    existing_apartments,
    new_apartments,
    storage_summary,
    apartment_mix,
    readiness_percentage
  )
  select
    slug,
    name,
    location,
    city,
    neighborhood,
    address,
    google_maps_url,
    google_maps_embed_url,
    project_type,
    marketing_status,
    tagline,
    description,
    logo_mark,
    key_facts,
    floors,
    units,
    occupancy,
    parking_summary,
    buildings,
    existing_apartments,
    new_apartments,
    storage_summary,
    apartment_mix,
    readiness_percentage
  from project_rows
  on conflict (slug) do update set
    name = excluded.name,
    location = excluded.location,
    city = excluded.city,
    neighborhood = excluded.neighborhood,
    address = excluded.address,
    google_maps_url = excluded.google_maps_url,
    google_maps_embed_url = excluded.google_maps_embed_url,
    project_type = excluded.project_type,
    marketing_status = excluded.marketing_status,
    tagline = excluded.tagline,
    description = excluded.description,
    logo_mark = excluded.logo_mark,
    key_facts = excluded.key_facts,
    floors = excluded.floors,
    units = excluded.units,
    occupancy = excluded.occupancy,
    parking_summary = excluded.parking_summary,
    buildings = excluded.buildings,
    existing_apartments = excluded.existing_apartments,
    new_apartments = excluded.new_apartments,
    storage_summary = excluded.storage_summary,
    apartment_mix = excluded.apartment_mix,
    readiness_percentage = excluded.readiness_percentage,
    updated_at = now()
  returning id, slug
),
seed_projects as (
  select upserted_projects.id, project_rows.slug, project_rows.apartment_offset
  from upserted_projects
  join project_rows on project_rows.slug = upserted_projects.slug
),
apartment_base as (
  select
    seed_projects.id as project_id,
    seed_projects.apartment_offset,
    series.item,
    series.item - 1 as apartment_index,
    seed_projects.apartment_offset + series.item + 3 as floor_value,
    case ((series.item - 1) % 3)
      when 0 then 4
      when 1 then 5
      else 3
    end as rooms_value
  from seed_projects
  cross join generate_series(1, 6) as series(item)
),
apartment_rows as (
  select
    project_id,
    floor_value::text || '0' || item::text as number,
    floor_value as floor,
    rooms_value as rooms,
    92 + rooms_value * 12 + apartment_index * 3 as apartment_area,
    12 + apartment_index * 2 as balcony_area,
    case when apartment_index = 0 then 28 else 0 end as garden_area,
    case when apartment_index % 2 = 0 then 'חניה אחת' else '2 חניות' end as parking,
    case when apartment_index % 3 = 0 then 'מחסן 6 מ"ר' else 'מחסן 4 מ"ר' end as storage,
    case (apartment_index % 4)
      when 0 then 'דרום מערב'
      when 1 then 'צפון מזרח'
      when 2 then 'מערב'
      else 'דרום'
    end as direction,
    3450000 + apartment_offset * 80000 + apartment_index * 190000 as price,
    3330000 + apartment_offset * 80000 + apartment_index * 190000 as special_price,
    case (apartment_index % 5)
      when 0 then 'available'
      when 1 then 'option'
      when 2 then 'reserved'
      when 3 then 'sold'
      else 'notMarketing'
    end as status,
    case when apartment_index <> 4 then 'attached' else 'missing' end as plan_file_status,
    case
      when apartment_index = 4 then 'לא לשיווק עד אישור מחיר'
      else 'תוכנית דירה זמינה לדמו'
    end as notes,
    item as sort_order
  from apartment_base
)
insert into public.apartments (
  project_id,
  number,
  floor,
  rooms,
  apartment_area,
  balcony_area,
  garden_area,
  parking,
  storage,
  direction,
  price,
  special_price,
  status,
  plan_file_status,
  notes,
  sort_order
)
select
  project_id,
  number,
  floor,
  rooms,
  apartment_area,
  balcony_area,
  garden_area,
  parking,
  storage,
  direction,
  price,
  special_price,
  status,
  plan_file_status,
  notes,
  sort_order
from apartment_rows
on conflict (project_id, number) do update set
  floor = excluded.floor,
  rooms = excluded.rooms,
  apartment_area = excluded.apartment_area,
  balcony_area = excluded.balcony_area,
  garden_area = excluded.garden_area,
  parking = excluded.parking,
  storage = excluded.storage,
  direction = excluded.direction,
  price = excluded.price,
  special_price = excluded.special_price,
  status = excluded.status,
  plan_file_status = excluded.plan_file_status,
  notes = excluded.notes,
  sort_order = excluded.sort_order,
  updated_at = now();
